# Site settings
title: Raleigh Bike Polo
email: willy@raleighbikepolo.club
copyright_name: Raleigh Bike Polo
github_username: rbpclub

collections:
  blog:
  teams:
  people:

# used to estimate reading time
wpm: 150

port: 4444
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
